before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: flyscrape
    main: ./cmd/flyscrape
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -extldflags "-static"
      - -X github.com/philippta/flyscrape.Version={{.Tag}}
    flags:
      - -mod=readonly
    tags:
      - osusergo
      - netgo

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
